lang: vi
title: Kinh Thánh Lược Truyện
tagline: Phiên bản đơn giản, dễ hiểu của Kinh Thánh
description: >-
  Phiên bản tóm lược đơn giản, dễ hiểu của Kinh Thánh.
  Dành cho người mới tìm hiểu và người yêu thích Kinh Thánh.
url: https://kinhthanhluoctruyen.com
baseurl: ""
logo: /assets/img/logo.png
email: dathoangnd@gmail.com
google_site_verification: S3PRKhXN-0Ac6HeIv9IOQ45skoclF8hreE3knnYJJJc

theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

collections:
  bible:
    output: true
    permalink: /:path/

defaults:
  - scope:
      path: ""
    values:
      image: /assets/img/thumbnail.png

  - scope:
      path: ""
      type: bible
    values:
      layout: reader

feed:
  collections:
    bible:
      path: /bible.xml

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/